export const typography = {
	fontFamily: {
		base: ["DM Sans", "system-ui", "sans-serif"],
	},
	"heading-1": {
		fontSize: "2rem",
		fontWeight: 700,
		lineHeight: "2rem",
		letterSpacing: "-0.06rem",
	},
	"heading-2": {
		fontSize: "1.5rem",
		fontWeight: 700,
		lineHeight: "1.938rem",
		letterSpacing: "-0.06rem",
	},
	"heading-3": {
		fontSize: "1.25rem",
		fontWeight: 700,
		lineHeight: "1.625rem",
		letterSpacing: "-0.06rem",
	},
	"heading-4": {
		fontSize: "1.125rem",
		fontWeight: 700,
		lineHeight: "1.438rem",
		letterSpacing: "-0.06rem",
	},
	"body-large-bold": {
		fontSize: "1.125rem",
		fontWeight: 700,
		lineHeight: "1.688rem",
		letterSpacing: "-0.031rem",
	},
	"body-large-medium": {
		fontSize: "1.125rem",
		fontWeight: 500,
		lineHeight: "1.688rem",
		letterSpacing: "-0.031rem",
	},
	"body-large-regular": {
		fontSize: "1.125rem",
		fontWeight: 400,
		lineHeight: "1.688rem",
		letterSpacing: "-0.031rem",
	},
	"body-normal-bold": {
		fontSize: "1rem",
		fontWeight: 700,
		lineHeight: "1.5rem",
		letterSpacing: "-0.031rem",
	},
	"body-normal-medium": {
		fontSize: "1rem",
		fontWeight: 500,
		lineHeight: "1.5rem",
		letterSpacing: "-0.031rem",
	},
	"body-normal-regular": {
		fontSize: "1rem",
		fontWeight: 400,
		lineHeight: "1.5rem",
		letterSpacing: "-0.031rem",
	},
	"body-small-regular": {
		fontSize: "0.875rem",
		fontWeight: 400,
		lineHeight: "1.3125rem",
		letterSpacing: "0rem",
	},
	"input-label": {
		fontSize: "0.75rem",
		fontWeight: 400,
		lineHeight: "0.75rem",
		letterSpacing: "0rem",
	},
	"input-label-small": {
		fontSize: "0.75rem",
		fontWeight: 400,
		lineHeight: "0.75rem",
		letterSpacing: "0rem",
	},
	"input-placeholder": {
		fontSize: "0.875rem",
		fontWeight: 400,
		lineHeight: "1.25rem",
		letterSpacing: "0rem",
	},
	"input-helper": {
		fontSize: "0.75rem",
		fontWeight: 400,
		lineHeight: "1.0625rem",
		letterSpacing: "0rem",
	},
	"button-large": {
		fontSize: "1rem",
		fontWeight: 500,
		lineHeight: "1.375rem",
		letterSpacing: "-0.031rem",
	},
	"button-small": {
		fontSize: "0.875rem",
		fontWeight: 500,
		lineHeight: "1.25rem",
		letterSpacing: "-0.031rem",
	},
	"heading-5": {
		fontSize: "1rem",
		fontWeight: 600,
		lineHeight: "1.25rem",
		letterSpacing: "-0.025rem",
	},
} as const;
